### ISSUE TITLE
Launching a root terminal using desktop-defaults-run -t -r doesn't work

### ISSUE THREAD

**Issue by BrandonIrizarry** [antiX-Linux/desktop-session-antix#3]
Hey, 

First, I have to say I'm an AntiX user, and I'm enjoying it!  However, I found that launching a root terminal at the command line using `desktop-defaults-run -t -r` doesn't work!  However, consider the following stanza of code, starting on line 78:

```
if [ "$exec_root" = 1 ]; then 
    gksu -u root "$Exec $xtraargs $args" 2>/dev/null &
    exit
```
If I eliminate the spaces in the expression `"$Exec $xtraargs $args"`, it works; that is, the above is now

```
if [ "$exec_root" = 1 ]; then 
    gksu -u root "$Exec$xtraargs$args" 2>/dev/null &
    exit
```

I'm not too expert on Bash, so I hope this fixes the problem definitively.

Thanks for your attention.

**Comment by anticapitalista** [comment]
Thanks - Now fixed
